packages:
  - "packages/*"
  - "apps/*"
allowBuilds:
  esbuild: true
  "@google/genai": true
  "@nestjs/core": true
  "@prisma/client": true
  "@prisma/engines": true
  prisma: true
  protobufjs: true
  msw: true
